clc;
close all;
clear all;
R=input('Enter the distence between the transmitter and receiver in km');
D=input ('Enter the Antenna Diameter in meter');
Ae=input('Enter the Aperture Efficiency of the antenna, acceptable value in the range(0 to 1)'); 
f=input('Enter the Operating Frequency');
T=input('Enter system Noise Temperature in Kelvin');
CN=0:1:100; 
c=3*10^8;
% link Noise Power Budget
k=-228.6; 
Ts=10*log10(T); 
B=10*log10(25*10^6); 
N=k+Ts+B; 
Pr=N+CN;
lamda=c/f; 
Gt=10*log10(Ae*(pi*D/lamda)^2); 
Lp=10*log10((4*pi*R/lamda)^2); 
Gr=-31; 
Lp=-Lp; 
Margin=6;
Pt=Pr-(Gt+Gr+Lp)+Margin; 
Ptw =10.^(Pt/10);
plot(CNup,Ptw,'LineWidth',1.5);
xlabel('C/N ratio in dB---->');
ylabel('Transmitted Power Pt in Watt----->');
title('C/N Versus Pt');
grid on;
