disp('cell splitting');
b1=input('enter the number of base station');
n1=input('enter the number of chnnnels of base station');
t1=b1*n1;
disp('total num of channels before cell splitting');
disp(t1);
m1=input('enter num of microcells');
b2=b1+m1;
disp('num of base station after cell splitting');
disp(b2);
t2=b2*n1;
disp('total num of channels after cell splitting');

disp(t2);
disp('cell sectoring');
c1=input('enter number of trafic channels per cells');
call1=input('enter num of calls/hr for c1');
c2=c1/3;
call2=input('enter num of calls/hr for c2');
ns1=input('enter num of sectors for 120 degree');
capacity=ns1*call2;
dif=call1-capacity;
percentdif=(dif/call1)*100;
disp('cell capacity of unsectored system');
disp(call1);
disp('cell capacity of 120 degree system');
disp(capacity);
disp('decrease in cell capacity');
disp(percentdif);
