clc; close all; clear all;
u1 = 1:8;
h = [0.4 1 0.4];
figure;
subplot(2,1,1);
stem(u1);
axis([0 10 0 10]);
title('Input signal');
subplot(2,1,2);
stem(h, '^');
axis([0 10 0 2]);
title('Channel impulse response');
N = length(u1);
y_lin = conv(u1, h);
y_circ = cconv(u1, h, N);
figure;
stem(y_lin, 'x');
hold on;
stem(y_circ, 'o');
title(['Convolution Results, N=', int2str(N)]);
legend('Linear', 'Circular', 'Location', 'northwest');
L = length(h);
ucp = u1(N-L+1:N); 
u2 = [ucp u1];     
y_lin_cp = conv(u2, h);
y_lin_cp = y_lin_cp(L+1:end); 
figure;
stem(y_lin_cp, 'x');
hold on;
stem(y_circ, 'o');
title('Convolution Results with Cyclic Prefix');
legend('Linear with CP', 'Circular', 'Location', 'northwest');
